### ISSUE TITLE
Put all the images into a Single Directory

### ISSUE THREAD

**Issue by SpiderMath** [caseyCantCode/discordImageGenImages#1]
You have provided a lot of files, which makes it look pretty damn messy. So what about like putting all the images into a Single Image directory?
That would make it look more neat not gonna lie

**Comment by caseyCantCode** [comment]
do you use this repo lmao

**Comment by SpiderMath** [comment]
Kinda and Kinda not

**Comment by caseyCantCode** [comment]
ill do it tmr cause i have to sleep soon but thanks for the suggestion!
